### PR TITLE
fixed the tags and category

### PR DESCRIPTION
**Pull request by thejmdw**
`git fetch --all`
`git checkout thejmdw-tags-categories`

_**An Author should now have the ability to create a tag or a category**_

### CODE REVIEW

**Review by gqgonzales — APPROVED** [review]
Bellisimo. Works as expected!

**Review by anmonzi — APPROVED** [review]
Good to go!

**Comment by thejmdw** [comment]
`git fetch --all`
`git checkout thejmdw-tags-categories`

_**An Author should now have the ability to create a tag or a category**_

### _**Merged Ashton's into this and added ability for the Admin to approve**_

_**follow the first two steps**_

_**sign in as an Author**_
_**go to the All Posts Tab**_
_should only see approved posts_

_**sign in as Steve or another Admin**_
_**go to the All Posts Tab**_
_should see all posts regardless of approval status_

_**should have the ability to approve and un-approve posts**_

**Review by anmonzi — APPROVED** [review]
Approved again, works great!

**Review by gqgonzales — APPROVED** [review]

**Pull request merged**
